script: 'ci/travis.rb'
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - "GEM=railties"
    - "GEM=ap,am,amo,as"
    - "GEM=ar:mysql"
    - "GEM=ar:mysql2"
    - "GEM=ar:sqlite3"
    - "GEM=ar:postgresql"
  global:
    - "RUBY_HEAP_MIN_SLOTS=1000000"
    - "RUBY_HEAP_SLOTS_INCREMENT=1000000"
    - "RUBY_HEAP_SLOTS_GROWTH_FACTOR=1"
    - "RUBY_GC_MALLOC_LIMIT=1000000000"
    - "RUBY_HEAP_FREE_MIN=500000"
    - "RUBY_FREE_MIN=$RUBY_HEAP_FREE_MIN"
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "YA1alef1ESHWGFNVwvmVGCkMe4cUy4j+UcNvMUESraceiAfVyRMAovlQBGs6\n9kBRm7DHYBUXYC2ABQoJbQRLDr/1B5JPf/M8+Qd7BKu8tcDC03U01SMHFLpO\naOs/HLXcDxtnnpL07tGVsm0zhMc5N8tq4/L3SHxK7Vi+TacwQzI="
bundler_args: --path vendor/bundle --without test
